### ISSUE TITLE
Crash on Android 7.1 after loading 24/24

### ISSUE THREAD

**Issue by LordierClaw** [quochung-cyou/SPOJ_RankTracker_PTIT#1]
Same as title
pls fix I want to track my idol's progress

**Comment by quochung-cyou** [comment]
Fixed


https://github.com/quochung-cyou/SPOJPTIT-D21-Tracking/commit/0f02ca83444f823560feeed906a427449f3bd778

Build:
https://github.com/quochung-cyou/SPOJPTIT-D21-Tracking/releases/tag/1.3
